spring:
  config:
    activate:
      on-profile: ${SPRING_PROFILES_ACTIVE:dev}

springdoc:
  api-docs:
    version: OPENAPI_3_0

  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/register_db}
    username: ${SPRING_DATASOURCE_USERNAME:local}
    password: ${SPRING_DATASOURCE_PASSWORD:local123}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}

security:
  jwt:
      secret: ${JWT_SECRET:12123581251298035890123980512890350981298053295132253802531925312352138923589}
      expiration: ${JWT_EXPIRATION:3600000}

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin123}
  bucket-name: ${MINIO_BUCKET_NAME:eatz-images}
