spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
      continue-on-error: false
      encoding: UTF-8

  datasource:
    driver-class-name: org.h2.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:sa}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
