spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: always
      continue-on-error: false
      encoding: UTF-8

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/register_db}
    username: ${SPRING_DATASOURCE_USERNAME:local}
    password: ${SPRING_DATASOURCE_PASSWORD:local123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
